apiVersion: apps/v1
kind: Deployment
metadata:
  name: cubeproject
  labels:
    app: api-mask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-mask
  template:
    metadata:
      labels:
        app: api-mask
    spec:
      containers:
      - name: api-mask
        image: artprojectt/kube_project
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api-mask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003
