apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-streamlit-deployment
  labels:
    app: ml-streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-streamlit
  template:
    metadata:
      labels:
        app: ml-streamlit
    spec:
      containers:
      - name: ml-streamlit
        image: artprojectt/mlstreamlit
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ml-streamlit-service
spec:
  type: NodePort
  selector:
    app: ml-streamlit
  ports:
    - protocol: TCP
      port: 8501
      nodePort: 30004
      targetPort: 8501
